import BitField from './BitField';
export type Permission = keyof typeof Permissions.bits;
export type PermissionsResolvable = keyof typeof Permissions.bits | number | bigint | PermissionsResolvable[];
export default class Permissions extends BitField {
    static bits: {
        CreateInstantInvite: number;
        KickMembers: number;
        BanMembers: number;
        Administrator: number;
        ManageChannels: number;
        ManageGuild: number;
        AddReactions: number;
        ViewAuditLog: number;
        PrioritySpeaker: number;
        Stream: number;
        ViewChannel: number;
        SendMessages: number;
        SendTTSMessages: number;
        ManageMessages: number;
        EmbedLinks: number;
        AttachFiles: number;
        ReadMessageHistory: number;
        MentionEveryone: number;
        UseExternalEmojis: number;
        ViewGuildInsights: number;
        Connect: number;
        Speak: number;
        MuteMembers: number;
        DeafenMembers: number;
        MoveMembers: number;
        UseVAD: number;
        ChangeNickname: number;
        ManageNicknames: number;
        ManageRoles: number;
        ManageWebhooks: number;
        ManageGuildExpressions: number;
        UseApplicationCommands: number;
        RequestToSpeak: number;
        ManageEvents: number;
        ManageThreads: number;
        CreatePublicThreads: number;
        CreatePrivateThreads: number;
        UseExternalStickers: number;
        SendMessagesInThreads: number;
        UseEmbeddedActivities: number;
        ModerateMembers: number;
        ViewCreatorMonetizationAnalytics: number;
        UseSoundboard: number;
        CreateGuildExpressions: number;
        CreateEvents: number;
        UseExternalSounds: number;
        SendVoiceMessages: number;
        SendPolls: number;
        UseExternalApps: number;
    };
    static all: number;
    constructor(...bits: PermissionsResolvable[]);
    has(bit: PermissionsResolvable): boolean;
}
